USE [WardrobeDB]
GO

/****** Object:  Table [dbo].[tblOccasion]    Script Date: 10/17/2016 10:51:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblOccasion](
	[OccasionID] [int] IDENTITY(1,1) NOT NULL,
	[OccasionName] [nchar](10) NOT NULL,
 CONSTRAINT [PK_tblOccasion] PRIMARY KEY CLUSTERED 
(
	[OccasionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

