//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblWardrobe
    {
        public int WardrobeID { get; set; }
        [Display(Name = "Name")]
        public string ClothingName { get; set; }
        public string PhotoLocaion { get; set; }
        [Display(Name = "Color")]
        public string ClothingColor { get; set; }
        [Display(Name = "Type")]
        public int TypeID { get; set; }
        [Display(Name = "Season")]
        public int SeasonID { get; set; }
        [Display(Name = "Occasion")]
        public int OccasionID { get; set; }
        public Nullable<int> OutfitID { get; set; }
    
        public virtual tblOccasion tblOccasion { get; set; }
        public virtual tblOutfit tblOutfit { get; set; }
        public virtual tblSeason tblSeason { get; set; }
        public virtual tblType tblType { get; set; }
    }
}
